package de.htwberlin.dao;

import java.sql.SQLException;
import java.util.List;

import de.htwberlin.object.Fahrzeug;

/**
 * JavaDoc generated by ChatGPT
 * The FahrzeugDao interface provides methods to access and manipulate Fahrzeug objects in the database.
 */
public interface FahrzeugDao {

    /**
     * Retrieves all Fahrzeug objects from the database.
     *
     * @return A list of all Fahrzeug objects.
     * @throws SQLException If an SQL exception occurs.
     */
    public List<Fahrzeug> getAllFahzeuge() throws SQLException;

    /**
     * Retrieves a Fahrzeug object by its ID.
     *
     * @param fzId The ID of the Fahrzeug.
     * @return The Fahrzeug object.
     * @throws SQLException If an SQL exception occurs.
     */
    public Fahrzeug getFahrzeugById(long fzId) throws SQLException;

    /**
     * Inserts a new Fahrzeug object into the database.
     *
     * @param fahrzeug The Fahrzeug object to be inserted.
     * @throws SQLException If an SQL exception occurs.
     */
    public void insertFahrzeug(Fahrzeug fahrzeug) throws SQLException;

    /**
     * Updates an existing Fahrzeug object in the database.
     *
     * @param fahrzeug The Fahrzeug object to be updated.
     * @throws SQLException If an SQL exception occurs.
     */
    public void updateFahrzeug(Fahrzeug fahrzeug) throws SQLException;

    /**
     * Deletes a Fahrzeug object from the database by its ID.
     *
     * @param fzId The ID of the Fahrzeug to be deleted.
     * @throws SQLException If an SQL exception occurs.
     */
    public void deleteFzId(long fzId) throws SQLException;
}
