package de.htwberlin.dao;

import java.sql.SQLException;
import java.util.List;

import de.htwberlin.object.Mautkategorie;

/**
 * Javadoc generated by Chatpgpt The MautkategorieDao interface provides methods
 * for accessing and manipulating Mautkategorie objects in the database.
 */
public interface MautkategorieDao {

	/**
	 * Retrieves all Mautkategorie objects from the database.
	 * 
	 * @return A list of all Mautkategorie objects.
	 * @throws SQLException If an SQL error ocscurs.
	 */
	List<Mautkategorie> getAllMautkategorien() throws SQLException;

	/**
	 * Retrieves a specific Mautkategorie object from the database based on its
	 * identifier.
	 * 
	 * @param kategorieId The identifier of the Mautkategorie object.
	 * @return The Mautkategorie object with the specified identifier, or null if
	 *         not found.
	 * @throws SQLException If an SQL error occurs.
	 */
	Mautkategorie getMautkategorieById(int kategorieId) throws SQLException;

	/**
	 * Retrieves a specific Mautkategorie object from the database based on its
	 * SsKlId.
	 * 
	 * @param ssKlid The SsKlId of the Mautkategorie object.
	 * @return The Mautkategorie object with the specified SsKlId, or null if not
	 *         found.
	 * @throws SQLException If an SQL error occurs.
	 */
	/**
	 * Retrieves a specific Mautkategorie object from the database based on its
	 * SsKlId.
	 *
	 * @param ssKlid The SsKlId of the Mautkategorie object.
	 * @return The Mautkategorie object with the specified SsKlId, or null if not
	 *         found.
	 * @throws SQLException If an SQL error occurs.
	 */
	Mautkategorie getMautkategorieBySsKlId(int ssKlid, String achszahl) throws SQLException;
}