package de.htwberlin.dao;

import java.sql.SQLException;
import java.util.List;

import de.htwberlin.object.Mauterhebung;

/**
 * Javadoc generated by Chatpgpt The MauterhebungDao interface provides methods
 * to access and manipulate Mauterhebung objects in the database.
 */
public interface MauterhebungDao {

	/**
	 * Retrieves all Mauterhebung objects from the database.
	 *
	 * @return A list of all Mauterhebung objects.
	 * @throws SQLException If an SQL exception occurs.
	 */
	public List<Mauterhebung> getAllMauterhebungen() throws SQLException;

	/**
	 * Retrieves a Mauterhebung object by its ID.
	 *
	 * @param mautId The ID of the Mauterhebung.
	 * @return The Mauterhebung object.
	 * @throws SQLException If an SQL exception occurs.
	 */
	public Mauterhebung getMauterhebungById(long mautId) throws SQLException;

	/**
	 * Inserts a new Mauterhebung object into the database.
	 *
	 * @param mauterhebung The Mauterhebung object to be inserted.
	 * @throws SQLException If an SQL exception occurs.
	 */
	public void insertMauterhebung(Mauterhebung mauterhebung) throws SQLException;

	/**
	 * Updates an existing Mauterhebung object in the database.
	 *
	 * @param mauterhebung The Mauterhebung object to be updated.
	 * @throws SQLException If an SQL exception occurs.
	 */
	public void updateMauterhebung(Mauterhebung mauterhebung) throws SQLException;

	/**
	 * Deletes a Mauterhebung object from the database by its ID.
	 *
	 * @param mautId The ID of the Mauterhebung to be deleted.
	 * @throws SQLException If an SQL exception occurs.
	 */
	public void deleteMauterhebung(long mautId) throws SQLException;
}
